name: Release

'on':
  workflow_run:
    workflows:
      - Test
    types:
      - completed
env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'
  
jobs:
            
  release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.project.outputs.VERSION }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
        # set up Java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }} 
          cache: maven
          
      - name: Package with Maven
        run: >-
          mvn --batch-mode -Dcheckstyle.skip -DskipTests  package
      
        
        # github release    
      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: 0.2
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          
          # Upload Artifact
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
