name: Test
'on':
    workflow_run:
      workflows: ["Checkstyle"]
      types:
        - completed
jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name:  Maven   Test 
      run: xvfb-run mvn -Dcheckstyle.skip test 

    